name:                solarpiskell
version:             0.1.0.0
github:              "lalabuy948/solarpiskell"
license:             BSD3
author:              "Daniil Popov"
maintainer:          "lalabuy9948@gmail.com"
copyright:           "2019 Daniil Popov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lalabuy948/solarpiskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson

executables:
  solarpiskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solarpiskell
    - scotty
    - aeson

tests:
  solarpiskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solarpiskell
